[package]
name = "sarpa"
version = "0.1.1"
edition = "2021"
description = "A simple command-line argument parser with a builder API"
license = "MIT"
repository = "https://github.com/KostasDas/sarpa"
keywords = ["cli", "arguments", "parser", "args"]
categories = ["command-line-interface"]
